### ISSUE TITLE
user.Current does not work on linux/amd64 

### ISSUE THREAD

**Issue by VincenzoLaSpesa** [uriel-fanelli/tribes#1]
I can build tribes but, when I start it, it gives me an:

		2015/06/10 21:02:26 user: Current not implemented on linux/amd64

I made an horrible workaround ( in /tols/tools.go )

	// just gets the home directory. to be moved in "tools"
	
	func GetHomeDir() string {
		return os.Getenv("HOME")
	}

**Comment by uriel-fanelli** [comment]
I'm using linux on amd64 , then I'm pretty sure it works. :)

Most likely you need to run make.bash for this target to have it working.

https://golang.org/doc/install/source

howto:

1. set the env string GOARCH as amd64 and GOOS as linux, 
2. enter the ${GOROOT}/src and run ./make.bash


Sorry, I won't merge  the workaround: is a security bridge.
